/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import jakarta.mail.Message;
import jakarta.mail.MessagingException;
import jakarta.mail.Transport;
import org.example.objects.MessageObj;
import org.example.session.MS365Xoauth2Session;
import org.example.session.MailSession;
import org.example.type.HtmlMailWithImage;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.io.IOException;
import java.net.URISyntaxException;
import java.util.Objects;

class MS365Xoauth2SessionTest {

  @Test
  void testGmailTLSMailWithImage() throws MessagingException, URISyntaxException, IOException {
    String to = "your.recipient@email.com";
    String from = "john.doe@your.domain";

    MailSession noAuthSession = new MS365Xoauth2Session();

    MessageObj messageObj =
        MessageObj.builder()
            .from(from)
            .to(to)
            .subject("test with attachment")
            .body("body with attachment")
            .attachment(
                new File(
                    Objects.requireNonNull(MessageObj.class.getResource("/png-sample.png"))
                        .toURI()))
            .build();

    Message message = new HtmlMailWithImage().create(noAuthSession.getSession(), messageObj);
    Transport.send(message);
  }
}
