/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import jakarta.mail.Message;
import jakarta.mail.MessagingException;
import jakarta.mail.Transport;
import org.example.session.NoAuthSession;
import org.example.type.HtmlMailWithAttachment;
import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.net.URISyntaxException;

class NoAuthSessionTest {
    @Test
    void testMailWithAttachment() throws MessagingException, URISyntaxException, IOException {
        String to = "your.recipient@email.com";
        String from = "john.doe@your.domain";

        NoAuthSession noAuthSession = new NoAuthSession();
        Message message = new HtmlMailWithAttachment().create(
                noAuthSession.getSession(),
                from,
                to,
                "html mail test",
                "html mail body"
        );

        Transport.send(message);
    }
}
